name: PHPStan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [11.*, 12.*]
        include:
          - laravel: 11.*
            testbench: ^9.0
          - laravel: 12.*
            testbench: ^10.0

    name: PHPStan - P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          # Skip Larastan for Laravel 12 due to compatibility issues
          if [[ "${{ matrix.laravel }}" == "12.*" ]]; then
            composer remove "larastan/larastan" --dev --no-interaction --no-update
          fi
          composer update --prefer-dist --no-interaction

      - name: Run PHPStan
        run: |
          if [ -f vendor/bin/phpstan ]; then
            vendor/bin/phpstan analyse --error-format=github
          else
            echo "PHPStan not found (likely Laravel 12 matrix without Larastan), skipping static analysis"
            ls -la vendor/bin/ || echo "vendor/bin directory not found"
            exit 0
          fi