name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: [8.1, 8.2, 8.3, 8.4]
        laravel: [10.*, 11.*, 12.*]
        stability: [prefer-lowest, prefer-stable]
        include:
          # Add specific testbench versions for better compatibility
          - laravel: 10.*
            testbench: ^8.0
          - laravel: 11.*
            testbench: ^9.0
          - laravel: 12.*
            testbench: ^10.0
        exclude:
          # Laravel 11+ requires PHP 8.2+
          - laravel: 11.*
            php: 8.1
          # Laravel 12 requires PHP 8.2+
          - laravel: 12.*
            php: 8.1
          # PHP 8.4 only with stable dependencies for now
          - php: 8.4
            stability: prefer-lowest

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
          tools: composer:v2

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --with-dependencies
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --with-dependencies

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest --colors=always

  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Check code style (Pint)
        run: vendor/bin/pint --test

      - name: Execute static analysis (PHPStan)
        run: vendor/bin/phpstan analyse

      - name: Execute architecture tests
        run: vendor/bin/pest --group=arch --colors=always

  coverage:
    runs-on: ubuntu-latest
    name: Coverage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: xdebug
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Execute tests with coverage
        run: vendor/bin/pest --coverage --min=90

      - name: Execute type coverage
        run: vendor/bin/pest --type-coverage --min=90