name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        php: [8.2, 8.3, 8.4]
        laravel: [11.*, 12.*]
        stability: [prefer-stable]
        include:
          # Add specific testbench versions for better compatibility
          - laravel: 11.*
            testbench: ^9.0
          - laravel: 12.*
            testbench: ^10.0

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
          tools: composer:v2

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          # Skip Larastan for Laravel 12 due to compatibility issues
          if [[ "${{ matrix.laravel }}" == "12.*" ]]; then
            composer remove "larastan/larastan" --dev --no-interaction --no-update
          fi
          composer update --prefer-dist --no-interaction --${{ matrix.stability }}

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest --colors=always

  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction
          ls -la vendor/bin/ || echo "vendor/bin directory not found"

      - name: Check code style (Pint)
        run: |
          if [ -f vendor/bin/pint ]; then
            vendor/bin/pint --test
          else
            echo "Laravel Pint not found, skipping code style check"
            exit 0
          fi

      - name: Execute static analysis (PHPStan)
        run: |
          if [ -f vendor/bin/phpstan ]; then
            vendor/bin/phpstan analyse
          else
            echo "PHPStan not found (likely Laravel 12 matrix without Larastan), skipping static analysis"
            exit 0
          fi

      - name: Execute architecture tests
        run: vendor/bin/pest --group=arch --colors=always

  coverage:
    runs-on: ubuntu-latest
    name: Coverage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: xdebug
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --dev

      - name: Execute tests with coverage
        run: vendor/bin/pest --coverage --min=70

      - name: Execute type coverage
        run: vendor/bin/pest --type-coverage --min=70